# Generated by Django 2.1 on 2024-04-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Packet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(max_length=50)),
                ('source_ip', models.CharField(max_length=50)),
                ('destination_ip', models.CharField(max_length=50)),
                ('source_port', models.IntegerField()),
                ('destination_port', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('summary', models.TextField()),
            ],
        ),
    ]
